services:
  # A Static web service on Render
  - type: web
    name: akajuniorpro
    env: static
    buildCommand: npm run build:render
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18
